version: '3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        ports:
            - "9000:9000"
        volumes:
            - .:/var/www/html

    webserver:
        image: nginx:latest
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    db:
        image: mysql:8.0
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ndquang@2002
            MYSQL_DATABASE: wristwatches_db
            MYSQL_USER: ndquang
            MYSQL_PASSWORD: ndquang@2002
        volumes:
            - dbdata:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin
        restart: unless-stopped
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
        ports:
            - "8888:80"
        depends_on:
            - db

volumes:
    dbdata:
